# Tensorflow2.0 小练习

In [3]:
!pip install tensorflow
import tensorflow as tf
import numpy as np

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.51.0 requires protobuf<7,>=3.20, but you have protobuf 7.34.1 which is incompatible.


   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.8/351.2 MB 6.0 MB/s eta 0:00:59
   ---------------------------------------- 2.6/351.2 MB 7.7 MB/s eta 0:00:46
   ---------------------------------------- 3.9/351.2 MB 7.1 MB/s eta 0:00:50
    --------------------------------------- 5.2/351.2 MB 6.8 MB/s eta 0:00:52
    --------------------------------------- 6.6/351.2 MB 6.7 MB/s eta 0:00:52
    --------------------------------------- 7.9/351.2 MB 6.6 MB/s eta 0:00:53
   - -------------------------------------- 9.2/351.2 MB 6.5 MB/s eta 0:00:53
   - -------------------------------------- 10.5/351.2 MB 6.5 MB/s eta 0:00:53
   - -------------------------------------- 11.8/351.2 MB 6.4 MB/s eta 0:00:53
   - -------------------------------------- 13.1/351.2 MB 6.4 MB/s eta 0:00:53
   - -------------------------------------- 14.4/351.2 MB 6.4 MB/s eta 0:00:53
   - -------------------------------------- 14.4/351.2 MB 6.4 MB/s 

## 实现softmax函数

In [5]:
def softmax(x):
    x = tf.cast(x, tf.float32)
    # 技巧：每行减最大值，防止 exp(大数) 溢出，结果不变
    x_max = tf.reduce_max(x, axis=-1, keepdims=True)
    x_exp = tf.exp(x - x_max)
    # 除以每行总和，变成概率（每行加起来=1）
    prob_x = x_exp / tf.reduce_sum(x_exp, axis=-1, keepdims=True)
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [6]:
def sigmoid(x):
    x = tf.cast(x, tf.float32)
    # 公式：1 / (1 + e^(-x))
    prob_x = 1.0 / (1.0 + tf.exp(-x))
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [8]:
def softmax_ce(x, label):
    # x 已经是 softmax 概率，直接套公式：loss = -sum(y * log(p))
    # 加 1e-12 防止 log(0) 出现 nan
    loss = -tf.reduce_sum(label * tf.math.log(x + 1e-12), axis=-1)  # 每个样本
    return tf.reduce_mean(loss)  # 对 batch 取均值

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

np.True_

## 实现 sigmoid 交叉熵loss函数

In [16]:
def sigmoid_ce(x, label):
   x = tf.cast(x, tf.float32)
   label = tf.cast(label, tf.float32)
   loss = -(label * tf.math.log(x + 1e-12) +(1 - label) * tf.math.log(1 - x + 1e-12))
   return tf.reduce_mean(loss)

test_data = np.random.normal(size=[10]).astype(np.float32)
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[1. 0. 1. 0. 1. 0. 1. 0. 1. 1.]


np.True_